stages:
  prepare:
    cmd: python src/create_features_w_params.py
    deps:
      - data/data.csv
    outs:
      - data/pipeline.pkl
      - data/processed_train_data.csv
      - data/processed_test_data.csv
    params: 
      - features.test_split_perc
      - features.data_path
